sudo: false
language: go
go:
- 1.x
- master

before_install:
  - openssl aes-256-cbc -K $encrypted_6a8b95daeded_key -iv $encrypted_6a8b95daeded_iv
    -in deployment-creds.json.enc -out deployment-creds.json
    -d

install:
- go get -v -u -t ./...

script:
- go vet ./...
- go test -v -cover ./...
- go build -v ./...

deploy:
  provider: gae
  project: color-detection-service
